package bwapi;

/** Autogenerated, do not modify manually. */
class ClientData {
    // Do not modify.
    static final int[][] ALL_DYNAMIC_OFFSETS = new int[][]{
        {0, 3447004},
        {4823260, 5085404},
        {10586480, 10962628},
        {32242636, 32962644},
    };
    static final int DYNAMIC_OFFSET_SIZE = 4805304;
    static class Wrapper {
         WrappedBuffer buff = null;
    }
    private final Wrapper mainBuffer = new Wrapper();
    // dynamicBuffer can point to the same buffer as main or its own.
    private final Wrapper dynamicBuffer = new Wrapper();
    private final GameData gameData;
    ClientData() {
        gameData = new ClientData.GameData(0);
    }
    GameData gameData() {
        return gameData;
    }
    void setBuffer(WrappedBuffer buffer) {
        this.mainBuffer.buff = buffer;
        this.dynamicBuffer.buff = buffer;
    }
    void setDynamicBuffer(WrappedBuffer dynamicBuffer) {
        this.dynamicBuffer.buff = dynamicBuffer;
    }
    int getExtraOffset1() {
        return dynamicBuffer.buff.getSize() == DYNAMIC_OFFSET_SIZE ? 4823260 : 0;
    }
    int getExtraOffset2() {
        return dynamicBuffer.buff.getSize() == DYNAMIC_OFFSET_SIZE ? 10586480 : 0;
    }
    int getExtraOffset3() {
        return dynamicBuffer.buff.getSize() == DYNAMIC_OFFSET_SIZE ? 32242636 : 0;
    }
    class UnitCommand {
        static final int SIZE = 24;
        private final int myOffset;
        private final Wrapper wrapper;
        UnitCommand(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        int getTid() {
            int offset = myOffset + 0;
            return wrapper.buff.getInt(offset);
        }
        void setTid(int value) {
            mainBuffer.buff.putInt(myOffset + 0, value);
        }
        int getUnitIndex() {
            int offset = myOffset + 4;
            return wrapper.buff.getInt(offset);
        }
        void setUnitIndex(int value) {
            mainBuffer.buff.putInt(myOffset + 4, value);
        }
        int getTargetIndex() {
            int offset = myOffset + 8;
            return wrapper.buff.getInt(offset);
        }
        void setTargetIndex(int value) {
            mainBuffer.buff.putInt(myOffset + 8, value);
        }
        int getX() {
            int offset = myOffset + 12;
            return wrapper.buff.getInt(offset);
        }
        void setX(int value) {
            mainBuffer.buff.putInt(myOffset + 12, value);
        }
        int getY() {
            int offset = myOffset + 16;
            return wrapper.buff.getInt(offset);
        }
        void setY(int value) {
            mainBuffer.buff.putInt(myOffset + 16, value);
        }
        int getExtra() {
            int offset = myOffset + 20;
            return wrapper.buff.getInt(offset);
        }
        void setExtra(int value) {
            mainBuffer.buff.putInt(myOffset + 20, value);
        }
    }
    class GameData {
        static final int SIZE = 33017048;
        private final int myOffset;
        GameData(int myOffset) {
            this.myOffset = myOffset;
        }
        int getClient_version() {
            int offset = myOffset + 0;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setClient_version(int value) {
            mainBuffer.buff.putInt(myOffset + 0, value);
        }
        int getRevision() {
            int offset = myOffset + 4;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setRevision(int value) {
            mainBuffer.buff.putInt(myOffset + 4, value);
        }
        boolean isDebug() {
            int offset = myOffset + 8;
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setIsDebug(boolean value) {
            mainBuffer.buff.putByte(myOffset + 8, (byte) (value ? 1 : 0));
        }
        int getInstanceID() {
            int offset = myOffset + 12;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setInstanceID(int value) {
            mainBuffer.buff.putInt(myOffset + 12, value);
        }
        int getBotAPM_noselects() {
            int offset = myOffset + 16;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setBotAPM_noselects(int value) {
            mainBuffer.buff.putInt(myOffset + 16, value);
        }
        int getBotAPM_selects() {
            int offset = myOffset + 20;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setBotAPM_selects(int value) {
            mainBuffer.buff.putInt(myOffset + 20, value);
        }
        int getForceCount() {
            int offset = myOffset + 24;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setForceCount(int value) {
            mainBuffer.buff.putInt(myOffset + 24, value);
        }
        ForceData getForces(int i) {
            int offset = myOffset + 28 + 32 * 1 * i;
            return new ForceData(offset, dynamicBuffer);
        }
        int getPlayerCount() {
            int offset = myOffset + 188;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setPlayerCount(int value) {
            mainBuffer.buff.putInt(myOffset + 188, value);
        }
        PlayerData getPlayers(int i) {
            int offset = myOffset + 192 + 5788 * 1 * i;
            return new PlayerData(offset, dynamicBuffer);
        }
        int getInitialUnitCount() {
            int offset = myOffset + 69648;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setInitialUnitCount(int value) {
            mainBuffer.buff.putInt(myOffset + 69648, value);
        }
        UnitData getUnits(int i) {
            int offset = myOffset + 69656 + 336 * 1 * i;
            return new UnitData(offset, dynamicBuffer);
        }
        int getUnitArray(int i) {
            int offset = myOffset + 3429656 + 4 * 1 * i;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setUnitArray(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 3429656 + 4 * 1 * i, value);
        }
        BulletData getBullets(int i) {
            int offset = myOffset + 3436456 + 80 * 1 * i;
            return new BulletData(offset, dynamicBuffer);
        }
        int getNukeDotCount() {
            int offset = myOffset + 3444456;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setNukeDotCount(int value) {
            mainBuffer.buff.putInt(myOffset + 3444456, value);
        }
        Position getNukeDots(int i) {
            int offset = myOffset + 3444460 + 8 * 1 * i;
            return new Position(offset, dynamicBuffer);
        }
        int getGameType() {
            int offset = myOffset + 3446060;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setGameType(int value) {
            mainBuffer.buff.putInt(myOffset + 3446060, value);
        }
        int getLatency() {
            int offset = myOffset + 3446064;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setLatency(int value) {
            mainBuffer.buff.putInt(myOffset + 3446064, value);
        }
        int getLatencyFrames() {
            int offset = myOffset + 3446068;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setLatencyFrames(int value) {
            mainBuffer.buff.putInt(myOffset + 3446068, value);
        }
        int getLatencyTime() {
            int offset = myOffset + 3446072;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setLatencyTime(int value) {
            mainBuffer.buff.putInt(myOffset + 3446072, value);
        }
        int getRemainingLatencyFrames() {
            int offset = myOffset + 3446076;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setRemainingLatencyFrames(int value) {
            mainBuffer.buff.putInt(myOffset + 3446076, value);
        }
        int getRemainingLatencyTime() {
            int offset = myOffset + 3446080;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setRemainingLatencyTime(int value) {
            mainBuffer.buff.putInt(myOffset + 3446080, value);
        }
        boolean getHasLatCom() {
            int offset = myOffset + 3446084;
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setHasLatCom(boolean value) {
            mainBuffer.buff.putByte(myOffset + 3446084, (byte) (value ? 1 : 0));
        }
        boolean getHasGUI() {
            int offset = myOffset + 3446085;
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setHasGUI(boolean value) {
            mainBuffer.buff.putByte(myOffset + 3446085, (byte) (value ? 1 : 0));
        }
        int getReplayFrameCount() {
            int offset = myOffset + 3446088;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setReplayFrameCount(int value) {
            mainBuffer.buff.putInt(myOffset + 3446088, value);
        }
        int getRandomSeed() {
            int offset = myOffset + 3446092;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setRandomSeed(int value) {
            mainBuffer.buff.putInt(myOffset + 3446092, value);
        }
        int getFrameCount() {
            int offset = myOffset + 3446096;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setFrameCount(int value) {
            mainBuffer.buff.putInt(myOffset + 3446096, value);
        }
        int getElapsedTime() {
            int offset = myOffset + 3446100;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setElapsedTime(int value) {
            mainBuffer.buff.putInt(myOffset + 3446100, value);
        }
        int getCountdownTimer() {
            int offset = myOffset + 3446104;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setCountdownTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 3446104, value);
        }
        int getFps() {
            int offset = myOffset + 3446108;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setFps(int value) {
            mainBuffer.buff.putInt(myOffset + 3446108, value);
        }
        double getAverageFPS() {
            int offset = myOffset + 3446112;
            return dynamicBuffer.buff.getDouble(offset);
        }
        void setAverageFPS(double value) {
            mainBuffer.buff.putDouble(myOffset + 3446112, value);
        }
        int getMouseX() {
            int offset = myOffset + 3446120;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setMouseX(int value) {
            mainBuffer.buff.putInt(myOffset + 3446120, value);
        }
        int getMouseY() {
            int offset = myOffset + 3446124;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setMouseY(int value) {
            mainBuffer.buff.putInt(myOffset + 3446124, value);
        }
        boolean getMouseState(int i) {
            int offset = myOffset + 3446128 + 1 * 1 * i;
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setMouseState(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 3446128 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        boolean getKeyState(int i) {
            int offset = myOffset + 3446131 + 1 * 1 * i;
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setKeyState(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 3446131 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        int getScreenX() {
            int offset = myOffset + 3446388;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setScreenX(int value) {
            mainBuffer.buff.putInt(myOffset + 3446388, value);
        }
        int getScreenY() {
            int offset = myOffset + 3446392;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setScreenY(int value) {
            mainBuffer.buff.putInt(myOffset + 3446392, value);
        }
        boolean getFlags(int i) {
            int offset = myOffset + 3446396 + 1 * 1 * i;
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setFlags(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 3446396 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        int getMapWidth() {
            int offset = myOffset + 3446400;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setMapWidth(int value) {
            mainBuffer.buff.putInt(myOffset + 3446400, value);
        }
        int getMapHeight() {
            int offset = myOffset + 3446404;
            return dynamicBuffer.buff.getInt(offset);
        }
        void setMapHeight(int value) {
            mainBuffer.buff.putInt(myOffset + 3446404, value);
        }
        String getMapFileName() {
            int offset = myOffset + 3446408;
            return dynamicBuffer.buff.getString(offset, 261);
        }
        void setMapFileName(String value) {
            mainBuffer.buff.putString(myOffset + 3446408, 261, value);
        }
        String getMapPathName() {
            int offset = myOffset + 3446669;
            return dynamicBuffer.buff.getString(offset, 261);
        }
        void setMapPathName(String value) {
            mainBuffer.buff.putString(myOffset + 3446669, 261, value);
        }
        String getMapName() {
            int offset = myOffset + 3446930;
            return dynamicBuffer.buff.getString(offset, 33);
        }
        void setMapName(String value) {
            mainBuffer.buff.putString(myOffset + 3446930, 33, value);
        }
        String getMapHash() {
            int offset = myOffset + 3446963;
            return dynamicBuffer.buff.getString(offset, 41);
        }
        void setMapHash(String value) {
            mainBuffer.buff.putString(myOffset + 3446963, 41, value);
        }
        int getGroundHeight(int i, int j) {
            int offset = myOffset + 3447004 + 4 * 1 * j + 4 * 256 * i;
            return mainBuffer.buff.getInt(offset);
        }
        void setGetGroundHeight(int i, int j, int value) {
            mainBuffer.buff.putInt(myOffset + 3447004 + 4 * 1 * j + 4 * 256 * i, value);
        }
        boolean isWalkable(int i, int j) {
            int offset = myOffset + 3709148 + 1 * 1 * j + 1 * 1024 * i;
            return mainBuffer.buff.getByte(offset) != 0;
        }
        void setIsWalkable(int i, int j, boolean value) {
            mainBuffer.buff.putByte(myOffset + 3709148 + 1 * 1 * j + 1 * 1024 * i, (byte) (value ? 1 : 0));
        }
        boolean isBuildable(int i, int j) {
            int offset = myOffset + 4757724 + 1 * 1 * j + 1 * 256 * i;
            return mainBuffer.buff.getByte(offset) != 0;
        }
        void setIsBuildable(int i, int j, boolean value) {
            mainBuffer.buff.putByte(myOffset + 4757724 + 1 * 1 * j + 1 * 256 * i, (byte) (value ? 1 : 0));
        }
        boolean isVisible(int i, int j) {
            int offset = myOffset + 4823260 + 1 * 1 * j + 1 * 256 * i - getExtraOffset1();
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setIsVisible(int i, int j, boolean value) {
            mainBuffer.buff.putByte(myOffset + 4823260 + 1 * 1 * j + 1 * 256 * i - getExtraOffset1(), (byte) (value ? 1 : 0));
        }
        boolean isExplored(int i, int j) {
            int offset = myOffset + 4888796 + 1 * 1 * j + 1 * 256 * i - getExtraOffset1();
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setIsExplored(int i, int j, boolean value) {
            mainBuffer.buff.putByte(myOffset + 4888796 + 1 * 1 * j + 1 * 256 * i - getExtraOffset1(), (byte) (value ? 1 : 0));
        }
        boolean getHasCreep(int i, int j) {
            int offset = myOffset + 4954332 + 1 * 1 * j + 1 * 256 * i - getExtraOffset1();
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setHasCreep(int i, int j, boolean value) {
            mainBuffer.buff.putByte(myOffset + 4954332 + 1 * 1 * j + 1 * 256 * i - getExtraOffset1(), (byte) (value ? 1 : 0));
        }
        boolean isOccupied(int i, int j) {
            int offset = myOffset + 5019868 + 1 * 1 * j + 1 * 256 * i - getExtraOffset1();
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setIsOccupied(int i, int j, boolean value) {
            mainBuffer.buff.putByte(myOffset + 5019868 + 1 * 1 * j + 1 * 256 * i - getExtraOffset1(), (byte) (value ? 1 : 0));
        }
        short getMapTileRegionId(int i, int j) {
            int offset = myOffset + 5085404 + 2 * 1 * j + 2 * 256 * i;
            return mainBuffer.buff.getShort(offset);
        }
        void setMapTileRegionId(int i, int j, short value) {
            mainBuffer.buff.putShort(myOffset + 5085404 + 2 * 1 * j + 2 * 256 * i, value);
        }
        short getMapSplitTilesMiniTileMask(int i) {
            int offset = myOffset + 5216476 + 2 * 1 * i;
            return mainBuffer.buff.getShort(offset);
        }
        void setMapSplitTilesMiniTileMask(int i, short value) {
            mainBuffer.buff.putShort(myOffset + 5216476 + 2 * 1 * i, value);
        }
        short getMapSplitTilesRegion1(int i) {
            int offset = myOffset + 5226476 + 2 * 1 * i;
            return mainBuffer.buff.getShort(offset);
        }
        void setMapSplitTilesRegion1(int i, short value) {
            mainBuffer.buff.putShort(myOffset + 5226476 + 2 * 1 * i, value);
        }
        short getMapSplitTilesRegion2(int i) {
            int offset = myOffset + 5236476 + 2 * 1 * i;
            return mainBuffer.buff.getShort(offset);
        }
        void setMapSplitTilesRegion2(int i, short value) {
            mainBuffer.buff.putShort(myOffset + 5236476 + 2 * 1 * i, value);
        }
        int getRegionCount() {
            int offset = myOffset + 5246476;
            return mainBuffer.buff.getInt(offset);
        }
        void setRegionCount(int value) {
            mainBuffer.buff.putInt(myOffset + 5246476, value);
        }
        RegionData getRegions(int i) {
            int offset = myOffset + 5246480 + 1068 * 1 * i;
            return new RegionData(offset, mainBuffer);
        }
        int getStartLocationCount() {
            int offset = myOffset + 10586480 - getExtraOffset2();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setStartLocationCount(int value) {
            mainBuffer.buff.putInt(myOffset + 10586480 - getExtraOffset2(), value);
        }
        Position getStartLocations(int i) {
            int offset = myOffset + 10586484 + 8 * 1 * i - getExtraOffset2();
            return new Position(offset, dynamicBuffer);
        }
        boolean isInGame() {
            int offset = myOffset + 10586548 - getExtraOffset2();
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setIsInGame(boolean value) {
            mainBuffer.buff.putByte(myOffset + 10586548 - getExtraOffset2(), (byte) (value ? 1 : 0));
        }
        boolean isMultiplayer() {
            int offset = myOffset + 10586549 - getExtraOffset2();
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setIsMultiplayer(boolean value) {
            mainBuffer.buff.putByte(myOffset + 10586549 - getExtraOffset2(), (byte) (value ? 1 : 0));
        }
        boolean isBattleNet() {
            int offset = myOffset + 10586550 - getExtraOffset2();
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setIsBattleNet(boolean value) {
            mainBuffer.buff.putByte(myOffset + 10586550 - getExtraOffset2(), (byte) (value ? 1 : 0));
        }
        boolean isPaused() {
            int offset = myOffset + 10586551 - getExtraOffset2();
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setIsPaused(boolean value) {
            mainBuffer.buff.putByte(myOffset + 10586551 - getExtraOffset2(), (byte) (value ? 1 : 0));
        }
        boolean isReplay() {
            int offset = myOffset + 10586552 - getExtraOffset2();
            return dynamicBuffer.buff.getByte(offset) != 0;
        }
        void setIsReplay(boolean value) {
            mainBuffer.buff.putByte(myOffset + 10586552 - getExtraOffset2(), (byte) (value ? 1 : 0));
        }
        int getSelectedUnitCount() {
            int offset = myOffset + 10586556 - getExtraOffset2();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setSelectedUnitCount(int value) {
            mainBuffer.buff.putInt(myOffset + 10586556 - getExtraOffset2(), value);
        }
        int getSelectedUnits(int i) {
            int offset = myOffset + 10586560 + 4 * 1 * i - getExtraOffset2();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setSelectedUnits(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 10586560 + 4 * 1 * i - getExtraOffset2(), value);
        }
        int getSelf() {
            int offset = myOffset + 10586608 - getExtraOffset2();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setSelf(int value) {
            mainBuffer.buff.putInt(myOffset + 10586608 - getExtraOffset2(), value);
        }
        int getEnemy() {
            int offset = myOffset + 10586612 - getExtraOffset2();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setEnemy(int value) {
            mainBuffer.buff.putInt(myOffset + 10586612 - getExtraOffset2(), value);
        }
        int getNeutral() {
            int offset = myOffset + 10586616 - getExtraOffset2();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setNeutral(int value) {
            mainBuffer.buff.putInt(myOffset + 10586616 - getExtraOffset2(), value);
        }
        int getEventCount() {
            int offset = myOffset + 10586620 - getExtraOffset2();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setEventCount(int value) {
            mainBuffer.buff.putInt(myOffset + 10586620 - getExtraOffset2(), value);
        }
        Event getEvents(int i) {
            int offset = myOffset + 10586624 + 12 * 1 * i - getExtraOffset2();
            return new Event(offset, dynamicBuffer);
        }
        int getEventStringCount() {
            int offset = myOffset + 10706624 - getExtraOffset2();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setEventStringCount(int value) {
            mainBuffer.buff.putInt(myOffset + 10706624 - getExtraOffset2(), value);
        }
        String getEventStrings(int i) {
            int offset = myOffset + 10706628 + 1 * 256 * i - getExtraOffset2();
            return dynamicBuffer.buff.getString(offset, 256);
        }
        void setEventStrings(int i, String value) {
            mainBuffer.buff.putString(myOffset + 10706628 + 1 * 256 * i - getExtraOffset2(), 256, value);
        }
        int getStringCount() {
            int offset = myOffset + 10962628;
            return mainBuffer.buff.getInt(offset);
        }
        void setStringCount(int value) {
            mainBuffer.buff.putInt(myOffset + 10962628, value);
        }
        String getStrings(int i) {
            int offset = myOffset + 10962632 + 1 * 1024 * i;
            return mainBuffer.buff.getString(offset, 1024);
        }
        void setStrings(int i, String value) {
            mainBuffer.buff.putString(myOffset + 10962632 + 1 * 1024 * i, 1024, value);
        }
        int getShapeCount() {
            int offset = myOffset + 31442632;
            return mainBuffer.buff.getInt(offset);
        }
        void setShapeCount(int value) {
            mainBuffer.buff.putInt(myOffset + 31442632, value);
        }
        Shape getShapes(int i) {
            int offset = myOffset + 31442636 + 40 * 1 * i;
            return new Shape(offset, mainBuffer);
        }
        int getCommandCount() {
            int offset = myOffset + 32242636 - getExtraOffset3();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setCommandCount(int value) {
            mainBuffer.buff.putInt(myOffset + 32242636 - getExtraOffset3(), value);
        }
        Command getCommands(int i) {
            int offset = myOffset + 32242640 + 12 * 1 * i - getExtraOffset3();
            return new Command(offset, dynamicBuffer);
        }
        int getUnitCommandCount() {
            int offset = myOffset + 32482640 - getExtraOffset3();
            return dynamicBuffer.buff.getInt(offset);
        }
        void setUnitCommandCount(int value) {
            mainBuffer.buff.putInt(myOffset + 32482640 - getExtraOffset3(), value);
        }
        UnitCommand getUnitCommands(int i) {
            int offset = myOffset + 32482644 + 24 * 1 * i - getExtraOffset3();
            return new UnitCommand(offset, dynamicBuffer);
        }
        int getUnitSearchSize() {
            int offset = myOffset + 32962644;
            return mainBuffer.buff.getInt(offset);
        }
        void setUnitSearchSize(int value) {
            mainBuffer.buff.putInt(myOffset + 32962644, value);
        }
        unitFinder getXUnitSearch(int i) {
            int offset = myOffset + 32962648 + 8 * 1 * i;
            return new unitFinder(offset, mainBuffer);
        }
        unitFinder getYUnitSearch(int i) {
            int offset = myOffset + 32989848 + 8 * 1 * i;
            return new unitFinder(offset, mainBuffer);
        }
    }
    class Shape {
        static final int SIZE = 40;
        private final int myOffset;
        private final Wrapper wrapper;
        Shape(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        ShapeType getType() {
            int offset = myOffset + 0;
            return ShapeType.idToEnum[wrapper.buff.getInt(offset)];
        }
        void setType(ShapeType value) {
            mainBuffer.buff.putInt(myOffset + 0, value.id);
        }
        CoordinateType getCtype() {
            int offset = myOffset + 4;
            return CoordinateType.idToEnum[wrapper.buff.getInt(offset)];
        }
        void setCtype(CoordinateType value) {
            mainBuffer.buff.putInt(myOffset + 4, value.id);
        }
        int getX1() {
            int offset = myOffset + 8;
            return wrapper.buff.getInt(offset);
        }
        void setX1(int value) {
            mainBuffer.buff.putInt(myOffset + 8, value);
        }
        int getY1() {
            int offset = myOffset + 12;
            return wrapper.buff.getInt(offset);
        }
        void setY1(int value) {
            mainBuffer.buff.putInt(myOffset + 12, value);
        }
        int getX2() {
            int offset = myOffset + 16;
            return wrapper.buff.getInt(offset);
        }
        void setX2(int value) {
            mainBuffer.buff.putInt(myOffset + 16, value);
        }
        int getY2() {
            int offset = myOffset + 20;
            return wrapper.buff.getInt(offset);
        }
        void setY2(int value) {
            mainBuffer.buff.putInt(myOffset + 20, value);
        }
        int getExtra1() {
            int offset = myOffset + 24;
            return wrapper.buff.getInt(offset);
        }
        void setExtra1(int value) {
            mainBuffer.buff.putInt(myOffset + 24, value);
        }
        int getExtra2() {
            int offset = myOffset + 28;
            return wrapper.buff.getInt(offset);
        }
        void setExtra2(int value) {
            mainBuffer.buff.putInt(myOffset + 28, value);
        }
        int getColor() {
            int offset = myOffset + 32;
            return wrapper.buff.getInt(offset);
        }
        void setColor(int value) {
            mainBuffer.buff.putInt(myOffset + 32, value);
        }
        boolean isSolid() {
            int offset = myOffset + 36;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsSolid(boolean value) {
            mainBuffer.buff.putByte(myOffset + 36, (byte) (value ? 1 : 0));
        }
    }
    class Command {
        static final int SIZE = 12;
        private final int myOffset;
        private final Wrapper wrapper;
        Command(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        CommandType getType() {
            int offset = myOffset + 0;
            return CommandType.idToEnum[wrapper.buff.getInt(offset)];
        }
        void setType(CommandType value) {
            mainBuffer.buff.putInt(myOffset + 0, value.id);
        }
        int getValue1() {
            int offset = myOffset + 4;
            return wrapper.buff.getInt(offset);
        }
        void setValue1(int value) {
            mainBuffer.buff.putInt(myOffset + 4, value);
        }
        int getValue2() {
            int offset = myOffset + 8;
            return wrapper.buff.getInt(offset);
        }
        void setValue2(int value) {
            mainBuffer.buff.putInt(myOffset + 8, value);
        }
    }
    class Position {
        static final int SIZE = 8;
        private final int myOffset;
        private final Wrapper wrapper;
        Position(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        int getX() {
            int offset = myOffset + 0;
            return wrapper.buff.getInt(offset);
        }
        void setX(int value) {
            mainBuffer.buff.putInt(myOffset + 0, value);
        }
        int getY() {
            int offset = myOffset + 4;
            return wrapper.buff.getInt(offset);
        }
        void setY(int value) {
            mainBuffer.buff.putInt(myOffset + 4, value);
        }
    }
    class Event {
        static final int SIZE = 12;
        private final int myOffset;
        private final Wrapper wrapper;
        Event(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        EventType getType() {
            int offset = myOffset + 0;
            return EventType.idToEnum[wrapper.buff.getInt(offset)];
        }
        void setType(EventType value) {
            mainBuffer.buff.putInt(myOffset + 0, value.id);
        }
        int getV1() {
            int offset = myOffset + 4;
            return wrapper.buff.getInt(offset);
        }
        void setV1(int value) {
            mainBuffer.buff.putInt(myOffset + 4, value);
        }
        int getV2() {
            int offset = myOffset + 8;
            return wrapper.buff.getInt(offset);
        }
        void setV2(int value) {
            mainBuffer.buff.putInt(myOffset + 8, value);
        }
    }
    class RegionData {
        static final int SIZE = 1068;
        private final int myOffset;
        private final Wrapper wrapper;
        RegionData(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        int getId() {
            int offset = myOffset + 0;
            return wrapper.buff.getInt(offset);
        }
        void setId(int value) {
            mainBuffer.buff.putInt(myOffset + 0, value);
        }
        int islandID() {
            int offset = myOffset + 4;
            return wrapper.buff.getInt(offset);
        }
        void setIslandID(int value) {
            mainBuffer.buff.putInt(myOffset + 4, value);
        }
        int getCenter_x() {
            int offset = myOffset + 8;
            return wrapper.buff.getInt(offset);
        }
        void setCenter_x(int value) {
            mainBuffer.buff.putInt(myOffset + 8, value);
        }
        int getCenter_y() {
            int offset = myOffset + 12;
            return wrapper.buff.getInt(offset);
        }
        void setCenter_y(int value) {
            mainBuffer.buff.putInt(myOffset + 12, value);
        }
        int getPriority() {
            int offset = myOffset + 16;
            return wrapper.buff.getInt(offset);
        }
        void setPriority(int value) {
            mainBuffer.buff.putInt(myOffset + 16, value);
        }
        int getLeftMost() {
            int offset = myOffset + 20;
            return wrapper.buff.getInt(offset);
        }
        void setLeftMost(int value) {
            mainBuffer.buff.putInt(myOffset + 20, value);
        }
        int getRightMost() {
            int offset = myOffset + 24;
            return wrapper.buff.getInt(offset);
        }
        void setRightMost(int value) {
            mainBuffer.buff.putInt(myOffset + 24, value);
        }
        int getTopMost() {
            int offset = myOffset + 28;
            return wrapper.buff.getInt(offset);
        }
        void setTopMost(int value) {
            mainBuffer.buff.putInt(myOffset + 28, value);
        }
        int getBottomMost() {
            int offset = myOffset + 32;
            return wrapper.buff.getInt(offset);
        }
        void setBottomMost(int value) {
            mainBuffer.buff.putInt(myOffset + 32, value);
        }
        int getNeighborCount() {
            int offset = myOffset + 36;
            return wrapper.buff.getInt(offset);
        }
        void setNeighborCount(int value) {
            mainBuffer.buff.putInt(myOffset + 36, value);
        }
        int getNeighbors(int i) {
            int offset = myOffset + 40 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setNeighbors(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 40 + 4 * 1 * i, value);
        }
        boolean isAccessible() {
            int offset = myOffset + 1064;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsAccessible(boolean value) {
            mainBuffer.buff.putByte(myOffset + 1064, (byte) (value ? 1 : 0));
        }
        boolean isHigherGround() {
            int offset = myOffset + 1065;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsHigherGround(boolean value) {
            mainBuffer.buff.putByte(myOffset + 1065, (byte) (value ? 1 : 0));
        }
    }
    class ForceData {
        static final int SIZE = 32;
        private final int myOffset;
        private final Wrapper wrapper;
        ForceData(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        String getName() {
            int offset = myOffset + 0;
            return wrapper.buff.getString(offset, 32);
        }
        void setName(String value) {
            mainBuffer.buff.putString(myOffset + 0, 32, value);
        }
    }
    class PlayerData {
        static final int SIZE = 5788;
        private final int myOffset;
        private final Wrapper wrapper;
        PlayerData(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        String getName() {
            int offset = myOffset + 0;
            return wrapper.buff.getString(offset, 25);
        }
        void setName(String value) {
            mainBuffer.buff.putString(myOffset + 0, 25, value);
        }
        int getRace() {
            int offset = myOffset + 28;
            return wrapper.buff.getInt(offset);
        }
        void setRace(int value) {
            mainBuffer.buff.putInt(myOffset + 28, value);
        }
        int getType() {
            int offset = myOffset + 32;
            return wrapper.buff.getInt(offset);
        }
        void setType(int value) {
            mainBuffer.buff.putInt(myOffset + 32, value);
        }
        int getForce() {
            int offset = myOffset + 36;
            return wrapper.buff.getInt(offset);
        }
        void setForce(int value) {
            mainBuffer.buff.putInt(myOffset + 36, value);
        }
        boolean isAlly(int i) {
            int offset = myOffset + 40 + 1 * 1 * i;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsAlly(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 40 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        boolean isEnemy(int i) {
            int offset = myOffset + 52 + 1 * 1 * i;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsEnemy(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 52 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        boolean isNeutral() {
            int offset = myOffset + 64;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsNeutral(boolean value) {
            mainBuffer.buff.putByte(myOffset + 64, (byte) (value ? 1 : 0));
        }
        int getStartLocationX() {
            int offset = myOffset + 68;
            return wrapper.buff.getInt(offset);
        }
        void setStartLocationX(int value) {
            mainBuffer.buff.putInt(myOffset + 68, value);
        }
        int getStartLocationY() {
            int offset = myOffset + 72;
            return wrapper.buff.getInt(offset);
        }
        void setStartLocationY(int value) {
            mainBuffer.buff.putInt(myOffset + 72, value);
        }
        boolean isVictorious() {
            int offset = myOffset + 76;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsVictorious(boolean value) {
            mainBuffer.buff.putByte(myOffset + 76, (byte) (value ? 1 : 0));
        }
        boolean isDefeated() {
            int offset = myOffset + 77;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsDefeated(boolean value) {
            mainBuffer.buff.putByte(myOffset + 77, (byte) (value ? 1 : 0));
        }
        boolean getLeftGame() {
            int offset = myOffset + 78;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setLeftGame(boolean value) {
            mainBuffer.buff.putByte(myOffset + 78, (byte) (value ? 1 : 0));
        }
        boolean isParticipating() {
            int offset = myOffset + 79;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsParticipating(boolean value) {
            mainBuffer.buff.putByte(myOffset + 79, (byte) (value ? 1 : 0));
        }
        int getMinerals() {
            int offset = myOffset + 80;
            return wrapper.buff.getInt(offset);
        }
        void setMinerals(int value) {
            mainBuffer.buff.putInt(myOffset + 80, value);
        }
        int getGas() {
            int offset = myOffset + 84;
            return wrapper.buff.getInt(offset);
        }
        void setGas(int value) {
            mainBuffer.buff.putInt(myOffset + 84, value);
        }
        int getGatheredMinerals() {
            int offset = myOffset + 88;
            return wrapper.buff.getInt(offset);
        }
        void setGatheredMinerals(int value) {
            mainBuffer.buff.putInt(myOffset + 88, value);
        }
        int getGatheredGas() {
            int offset = myOffset + 92;
            return wrapper.buff.getInt(offset);
        }
        void setGatheredGas(int value) {
            mainBuffer.buff.putInt(myOffset + 92, value);
        }
        int getRepairedMinerals() {
            int offset = myOffset + 96;
            return wrapper.buff.getInt(offset);
        }
        void setRepairedMinerals(int value) {
            mainBuffer.buff.putInt(myOffset + 96, value);
        }
        int getRepairedGas() {
            int offset = myOffset + 100;
            return wrapper.buff.getInt(offset);
        }
        void setRepairedGas(int value) {
            mainBuffer.buff.putInt(myOffset + 100, value);
        }
        int getRefundedMinerals() {
            int offset = myOffset + 104;
            return wrapper.buff.getInt(offset);
        }
        void setRefundedMinerals(int value) {
            mainBuffer.buff.putInt(myOffset + 104, value);
        }
        int getRefundedGas() {
            int offset = myOffset + 108;
            return wrapper.buff.getInt(offset);
        }
        void setRefundedGas(int value) {
            mainBuffer.buff.putInt(myOffset + 108, value);
        }
        int getSupplyTotal(int i) {
            int offset = myOffset + 112 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setSupplyTotal(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 112 + 4 * 1 * i, value);
        }
        int getSupplyUsed(int i) {
            int offset = myOffset + 124 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setSupplyUsed(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 124 + 4 * 1 * i, value);
        }
        int getAllUnitCount(int i) {
            int offset = myOffset + 136 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setAllUnitCount(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 136 + 4 * 1 * i, value);
        }
        int getVisibleUnitCount(int i) {
            int offset = myOffset + 1072 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setVisibleUnitCount(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 1072 + 4 * 1 * i, value);
        }
        int getCompletedUnitCount(int i) {
            int offset = myOffset + 2008 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setCompletedUnitCount(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 2008 + 4 * 1 * i, value);
        }
        int getDeadUnitCount(int i) {
            int offset = myOffset + 2944 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setDeadUnitCount(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 2944 + 4 * 1 * i, value);
        }
        int getKilledUnitCount(int i) {
            int offset = myOffset + 3880 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setKilledUnitCount(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 3880 + 4 * 1 * i, value);
        }
        int getUpgradeLevel(int i) {
            int offset = myOffset + 4816 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setUpgradeLevel(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 4816 + 4 * 1 * i, value);
        }
        boolean getHasResearched(int i) {
            int offset = myOffset + 5068 + 1 * 1 * i;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setHasResearched(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 5068 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        boolean isResearching(int i) {
            int offset = myOffset + 5115 + 1 * 1 * i;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsResearching(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 5115 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        boolean isUpgrading(int i) {
            int offset = myOffset + 5162 + 1 * 1 * i;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsUpgrading(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 5162 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        int getColor() {
            int offset = myOffset + 5228;
            return wrapper.buff.getInt(offset);
        }
        void setColor(int value) {
            mainBuffer.buff.putInt(myOffset + 5228, value);
        }
        int getTotalUnitScore() {
            int offset = myOffset + 5232;
            return wrapper.buff.getInt(offset);
        }
        void setTotalUnitScore(int value) {
            mainBuffer.buff.putInt(myOffset + 5232, value);
        }
        int getTotalKillScore() {
            int offset = myOffset + 5236;
            return wrapper.buff.getInt(offset);
        }
        void setTotalKillScore(int value) {
            mainBuffer.buff.putInt(myOffset + 5236, value);
        }
        int getTotalBuildingScore() {
            int offset = myOffset + 5240;
            return wrapper.buff.getInt(offset);
        }
        void setTotalBuildingScore(int value) {
            mainBuffer.buff.putInt(myOffset + 5240, value);
        }
        int getTotalRazingScore() {
            int offset = myOffset + 5244;
            return wrapper.buff.getInt(offset);
        }
        void setTotalRazingScore(int value) {
            mainBuffer.buff.putInt(myOffset + 5244, value);
        }
        int getCustomScore() {
            int offset = myOffset + 5248;
            return wrapper.buff.getInt(offset);
        }
        void setCustomScore(int value) {
            mainBuffer.buff.putInt(myOffset + 5248, value);
        }
        int getMaxUpgradeLevel(int i) {
            int offset = myOffset + 5252 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setMaxUpgradeLevel(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 5252 + 4 * 1 * i, value);
        }
        boolean isResearchAvailable(int i) {
            int offset = myOffset + 5504 + 1 * 1 * i;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsResearchAvailable(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 5504 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        boolean isUnitAvailable(int i) {
            int offset = myOffset + 5551 + 1 * 1 * i;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsUnitAvailable(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 5551 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
    }
    class BulletData {
        static final int SIZE = 80;
        private final int myOffset;
        private final Wrapper wrapper;
        BulletData(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        int getId() {
            int offset = myOffset + 0;
            return wrapper.buff.getInt(offset);
        }
        void setId(int value) {
            mainBuffer.buff.putInt(myOffset + 0, value);
        }
        int getPlayer() {
            int offset = myOffset + 4;
            return wrapper.buff.getInt(offset);
        }
        void setPlayer(int value) {
            mainBuffer.buff.putInt(myOffset + 4, value);
        }
        int getType() {
            int offset = myOffset + 8;
            return wrapper.buff.getInt(offset);
        }
        void setType(int value) {
            mainBuffer.buff.putInt(myOffset + 8, value);
        }
        int getSource() {
            int offset = myOffset + 12;
            return wrapper.buff.getInt(offset);
        }
        void setSource(int value) {
            mainBuffer.buff.putInt(myOffset + 12, value);
        }
        int getPositionX() {
            int offset = myOffset + 16;
            return wrapper.buff.getInt(offset);
        }
        void setPositionX(int value) {
            mainBuffer.buff.putInt(myOffset + 16, value);
        }
        int getPositionY() {
            int offset = myOffset + 20;
            return wrapper.buff.getInt(offset);
        }
        void setPositionY(int value) {
            mainBuffer.buff.putInt(myOffset + 20, value);
        }
        double getAngle() {
            int offset = myOffset + 24;
            return wrapper.buff.getDouble(offset);
        }
        void setAngle(double value) {
            mainBuffer.buff.putDouble(myOffset + 24, value);
        }
        double getVelocityX() {
            int offset = myOffset + 32;
            return wrapper.buff.getDouble(offset);
        }
        void setVelocityX(double value) {
            mainBuffer.buff.putDouble(myOffset + 32, value);
        }
        double getVelocityY() {
            int offset = myOffset + 40;
            return wrapper.buff.getDouble(offset);
        }
        void setVelocityY(double value) {
            mainBuffer.buff.putDouble(myOffset + 40, value);
        }
        int getTarget() {
            int offset = myOffset + 48;
            return wrapper.buff.getInt(offset);
        }
        void setTarget(int value) {
            mainBuffer.buff.putInt(myOffset + 48, value);
        }
        int getTargetPositionX() {
            int offset = myOffset + 52;
            return wrapper.buff.getInt(offset);
        }
        void setTargetPositionX(int value) {
            mainBuffer.buff.putInt(myOffset + 52, value);
        }
        int getTargetPositionY() {
            int offset = myOffset + 56;
            return wrapper.buff.getInt(offset);
        }
        void setTargetPositionY(int value) {
            mainBuffer.buff.putInt(myOffset + 56, value);
        }
        int getRemoveTimer() {
            int offset = myOffset + 60;
            return wrapper.buff.getInt(offset);
        }
        void setRemoveTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 60, value);
        }
        boolean getExists() {
            int offset = myOffset + 64;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setExists(boolean value) {
            mainBuffer.buff.putByte(myOffset + 64, (byte) (value ? 1 : 0));
        }
        boolean isVisible(int i) {
            int offset = myOffset + 65 + 1 * 1 * i;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsVisible(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 65 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
    }
    class unitFinder {
        static final int SIZE = 8;
        private final int myOffset;
        private final Wrapper wrapper;
        unitFinder(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        int getUnitIndex() {
            int offset = myOffset + 0;
            return wrapper.buff.getInt(offset);
        }
        void setUnitIndex(int value) {
            mainBuffer.buff.putInt(myOffset + 0, value);
        }
        int getSearchValue() {
            int offset = myOffset + 4;
            return wrapper.buff.getInt(offset);
        }
        void setSearchValue(int value) {
            mainBuffer.buff.putInt(myOffset + 4, value);
        }
    }
    class UnitData {
        static final int SIZE = 336;
        private final int myOffset;
        private final Wrapper wrapper;
        UnitData(int myOffset, Wrapper wrapper) {
            this.wrapper = wrapper;
            this.myOffset = myOffset;
        }
        int getClearanceLevel() {
            int offset = myOffset + 0;
            return wrapper.buff.getInt(offset);
        }
        void setClearanceLevel(int value) {
            mainBuffer.buff.putInt(myOffset + 0, value);
        }
        int getId() {
            int offset = myOffset + 4;
            return wrapper.buff.getInt(offset);
        }
        void setId(int value) {
            mainBuffer.buff.putInt(myOffset + 4, value);
        }
        int getPlayer() {
            int offset = myOffset + 8;
            return wrapper.buff.getInt(offset);
        }
        void setPlayer(int value) {
            mainBuffer.buff.putInt(myOffset + 8, value);
        }
        int getType() {
            int offset = myOffset + 12;
            return wrapper.buff.getInt(offset);
        }
        void setType(int value) {
            mainBuffer.buff.putInt(myOffset + 12, value);
        }
        int getPositionX() {
            int offset = myOffset + 16;
            return wrapper.buff.getInt(offset);
        }
        void setPositionX(int value) {
            mainBuffer.buff.putInt(myOffset + 16, value);
        }
        int getPositionY() {
            int offset = myOffset + 20;
            return wrapper.buff.getInt(offset);
        }
        void setPositionY(int value) {
            mainBuffer.buff.putInt(myOffset + 20, value);
        }
        double getAngle() {
            int offset = myOffset + 24;
            return wrapper.buff.getDouble(offset);
        }
        void setAngle(double value) {
            mainBuffer.buff.putDouble(myOffset + 24, value);
        }
        double getVelocityX() {
            int offset = myOffset + 32;
            return wrapper.buff.getDouble(offset);
        }
        void setVelocityX(double value) {
            mainBuffer.buff.putDouble(myOffset + 32, value);
        }
        double getVelocityY() {
            int offset = myOffset + 40;
            return wrapper.buff.getDouble(offset);
        }
        void setVelocityY(double value) {
            mainBuffer.buff.putDouble(myOffset + 40, value);
        }
        int getHitPoints() {
            int offset = myOffset + 48;
            return wrapper.buff.getInt(offset);
        }
        void setHitPoints(int value) {
            mainBuffer.buff.putInt(myOffset + 48, value);
        }
        int getLastHitPoints() {
            int offset = myOffset + 52;
            return wrapper.buff.getInt(offset);
        }
        void setLastHitPoints(int value) {
            mainBuffer.buff.putInt(myOffset + 52, value);
        }
        int getShields() {
            int offset = myOffset + 56;
            return wrapper.buff.getInt(offset);
        }
        void setShields(int value) {
            mainBuffer.buff.putInt(myOffset + 56, value);
        }
        int getEnergy() {
            int offset = myOffset + 60;
            return wrapper.buff.getInt(offset);
        }
        void setEnergy(int value) {
            mainBuffer.buff.putInt(myOffset + 60, value);
        }
        int getResources() {
            int offset = myOffset + 64;
            return wrapper.buff.getInt(offset);
        }
        void setResources(int value) {
            mainBuffer.buff.putInt(myOffset + 64, value);
        }
        int getResourceGroup() {
            int offset = myOffset + 68;
            return wrapper.buff.getInt(offset);
        }
        void setResourceGroup(int value) {
            mainBuffer.buff.putInt(myOffset + 68, value);
        }
        int getKillCount() {
            int offset = myOffset + 72;
            return wrapper.buff.getInt(offset);
        }
        void setKillCount(int value) {
            mainBuffer.buff.putInt(myOffset + 72, value);
        }
        int getAcidSporeCount() {
            int offset = myOffset + 76;
            return wrapper.buff.getInt(offset);
        }
        void setAcidSporeCount(int value) {
            mainBuffer.buff.putInt(myOffset + 76, value);
        }
        int getScarabCount() {
            int offset = myOffset + 80;
            return wrapper.buff.getInt(offset);
        }
        void setScarabCount(int value) {
            mainBuffer.buff.putInt(myOffset + 80, value);
        }
        int getInterceptorCount() {
            int offset = myOffset + 84;
            return wrapper.buff.getInt(offset);
        }
        void setInterceptorCount(int value) {
            mainBuffer.buff.putInt(myOffset + 84, value);
        }
        int getSpiderMineCount() {
            int offset = myOffset + 88;
            return wrapper.buff.getInt(offset);
        }
        void setSpiderMineCount(int value) {
            mainBuffer.buff.putInt(myOffset + 88, value);
        }
        int getGroundWeaponCooldown() {
            int offset = myOffset + 92;
            return wrapper.buff.getInt(offset);
        }
        void setGroundWeaponCooldown(int value) {
            mainBuffer.buff.putInt(myOffset + 92, value);
        }
        int getAirWeaponCooldown() {
            int offset = myOffset + 96;
            return wrapper.buff.getInt(offset);
        }
        void setAirWeaponCooldown(int value) {
            mainBuffer.buff.putInt(myOffset + 96, value);
        }
        int getSpellCooldown() {
            int offset = myOffset + 100;
            return wrapper.buff.getInt(offset);
        }
        void setSpellCooldown(int value) {
            mainBuffer.buff.putInt(myOffset + 100, value);
        }
        int getDefenseMatrixPoints() {
            int offset = myOffset + 104;
            return wrapper.buff.getInt(offset);
        }
        void setDefenseMatrixPoints(int value) {
            mainBuffer.buff.putInt(myOffset + 104, value);
        }
        int getDefenseMatrixTimer() {
            int offset = myOffset + 108;
            return wrapper.buff.getInt(offset);
        }
        void setDefenseMatrixTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 108, value);
        }
        int getEnsnareTimer() {
            int offset = myOffset + 112;
            return wrapper.buff.getInt(offset);
        }
        void setEnsnareTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 112, value);
        }
        int getIrradiateTimer() {
            int offset = myOffset + 116;
            return wrapper.buff.getInt(offset);
        }
        void setIrradiateTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 116, value);
        }
        int getLockdownTimer() {
            int offset = myOffset + 120;
            return wrapper.buff.getInt(offset);
        }
        void setLockdownTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 120, value);
        }
        int getMaelstromTimer() {
            int offset = myOffset + 124;
            return wrapper.buff.getInt(offset);
        }
        void setMaelstromTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 124, value);
        }
        int getOrderTimer() {
            int offset = myOffset + 128;
            return wrapper.buff.getInt(offset);
        }
        void setOrderTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 128, value);
        }
        int getPlagueTimer() {
            int offset = myOffset + 132;
            return wrapper.buff.getInt(offset);
        }
        void setPlagueTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 132, value);
        }
        int getRemoveTimer() {
            int offset = myOffset + 136;
            return wrapper.buff.getInt(offset);
        }
        void setRemoveTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 136, value);
        }
        int getStasisTimer() {
            int offset = myOffset + 140;
            return wrapper.buff.getInt(offset);
        }
        void setStasisTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 140, value);
        }
        int getStimTimer() {
            int offset = myOffset + 144;
            return wrapper.buff.getInt(offset);
        }
        void setStimTimer(int value) {
            mainBuffer.buff.putInt(myOffset + 144, value);
        }
        int getBuildType() {
            int offset = myOffset + 148;
            return wrapper.buff.getInt(offset);
        }
        void setBuildType(int value) {
            mainBuffer.buff.putInt(myOffset + 148, value);
        }
        int getTrainingQueueCount() {
            int offset = myOffset + 152;
            return wrapper.buff.getInt(offset);
        }
        void setTrainingQueueCount(int value) {
            mainBuffer.buff.putInt(myOffset + 152, value);
        }
        int getTrainingQueue(int i) {
            int offset = myOffset + 156 + 4 * 1 * i;
            return wrapper.buff.getInt(offset);
        }
        void setTrainingQueue(int i, int value) {
            mainBuffer.buff.putInt(myOffset + 156 + 4 * 1 * i, value);
        }
        int getTech() {
            int offset = myOffset + 176;
            return wrapper.buff.getInt(offset);
        }
        void setTech(int value) {
            mainBuffer.buff.putInt(myOffset + 176, value);
        }
        int getUpgrade() {
            int offset = myOffset + 180;
            return wrapper.buff.getInt(offset);
        }
        void setUpgrade(int value) {
            mainBuffer.buff.putInt(myOffset + 180, value);
        }
        int getRemainingBuildTime() {
            int offset = myOffset + 184;
            return wrapper.buff.getInt(offset);
        }
        void setRemainingBuildTime(int value) {
            mainBuffer.buff.putInt(myOffset + 184, value);
        }
        int getRemainingTrainTime() {
            int offset = myOffset + 188;
            return wrapper.buff.getInt(offset);
        }
        void setRemainingTrainTime(int value) {
            mainBuffer.buff.putInt(myOffset + 188, value);
        }
        int getRemainingResearchTime() {
            int offset = myOffset + 192;
            return wrapper.buff.getInt(offset);
        }
        void setRemainingResearchTime(int value) {
            mainBuffer.buff.putInt(myOffset + 192, value);
        }
        int getRemainingUpgradeTime() {
            int offset = myOffset + 196;
            return wrapper.buff.getInt(offset);
        }
        void setRemainingUpgradeTime(int value) {
            mainBuffer.buff.putInt(myOffset + 196, value);
        }
        int getBuildUnit() {
            int offset = myOffset + 200;
            return wrapper.buff.getInt(offset);
        }
        void setBuildUnit(int value) {
            mainBuffer.buff.putInt(myOffset + 200, value);
        }
        int getTarget() {
            int offset = myOffset + 204;
            return wrapper.buff.getInt(offset);
        }
        void setTarget(int value) {
            mainBuffer.buff.putInt(myOffset + 204, value);
        }
        int getTargetPositionX() {
            int offset = myOffset + 208;
            return wrapper.buff.getInt(offset);
        }
        void setTargetPositionX(int value) {
            mainBuffer.buff.putInt(myOffset + 208, value);
        }
        int getTargetPositionY() {
            int offset = myOffset + 212;
            return wrapper.buff.getInt(offset);
        }
        void setTargetPositionY(int value) {
            mainBuffer.buff.putInt(myOffset + 212, value);
        }
        int getOrder() {
            int offset = myOffset + 216;
            return wrapper.buff.getInt(offset);
        }
        void setOrder(int value) {
            mainBuffer.buff.putInt(myOffset + 216, value);
        }
        int getOrderTarget() {
            int offset = myOffset + 220;
            return wrapper.buff.getInt(offset);
        }
        void setOrderTarget(int value) {
            mainBuffer.buff.putInt(myOffset + 220, value);
        }
        int getOrderTargetPositionX() {
            int offset = myOffset + 224;
            return wrapper.buff.getInt(offset);
        }
        void setOrderTargetPositionX(int value) {
            mainBuffer.buff.putInt(myOffset + 224, value);
        }
        int getOrderTargetPositionY() {
            int offset = myOffset + 228;
            return wrapper.buff.getInt(offset);
        }
        void setOrderTargetPositionY(int value) {
            mainBuffer.buff.putInt(myOffset + 228, value);
        }
        int getSecondaryOrder() {
            int offset = myOffset + 232;
            return wrapper.buff.getInt(offset);
        }
        void setSecondaryOrder(int value) {
            mainBuffer.buff.putInt(myOffset + 232, value);
        }
        int getRallyPositionX() {
            int offset = myOffset + 236;
            return wrapper.buff.getInt(offset);
        }
        void setRallyPositionX(int value) {
            mainBuffer.buff.putInt(myOffset + 236, value);
        }
        int getRallyPositionY() {
            int offset = myOffset + 240;
            return wrapper.buff.getInt(offset);
        }
        void setRallyPositionY(int value) {
            mainBuffer.buff.putInt(myOffset + 240, value);
        }
        int getRallyUnit() {
            int offset = myOffset + 244;
            return wrapper.buff.getInt(offset);
        }
        void setRallyUnit(int value) {
            mainBuffer.buff.putInt(myOffset + 244, value);
        }
        int getAddon() {
            int offset = myOffset + 248;
            return wrapper.buff.getInt(offset);
        }
        void setAddon(int value) {
            mainBuffer.buff.putInt(myOffset + 248, value);
        }
        int getNydusExit() {
            int offset = myOffset + 252;
            return wrapper.buff.getInt(offset);
        }
        void setNydusExit(int value) {
            mainBuffer.buff.putInt(myOffset + 252, value);
        }
        int getPowerUp() {
            int offset = myOffset + 256;
            return wrapper.buff.getInt(offset);
        }
        void setPowerUp(int value) {
            mainBuffer.buff.putInt(myOffset + 256, value);
        }
        int getTransport() {
            int offset = myOffset + 260;
            return wrapper.buff.getInt(offset);
        }
        void setTransport(int value) {
            mainBuffer.buff.putInt(myOffset + 260, value);
        }
        int getCarrier() {
            int offset = myOffset + 264;
            return wrapper.buff.getInt(offset);
        }
        void setCarrier(int value) {
            mainBuffer.buff.putInt(myOffset + 264, value);
        }
        int getHatchery() {
            int offset = myOffset + 268;
            return wrapper.buff.getInt(offset);
        }
        void setHatchery(int value) {
            mainBuffer.buff.putInt(myOffset + 268, value);
        }
        boolean getExists() {
            int offset = myOffset + 272;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setExists(boolean value) {
            mainBuffer.buff.putByte(myOffset + 272, (byte) (value ? 1 : 0));
        }
        boolean getHasNuke() {
            int offset = myOffset + 273;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setHasNuke(boolean value) {
            mainBuffer.buff.putByte(myOffset + 273, (byte) (value ? 1 : 0));
        }
        boolean isAccelerating() {
            int offset = myOffset + 274;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsAccelerating(boolean value) {
            mainBuffer.buff.putByte(myOffset + 274, (byte) (value ? 1 : 0));
        }
        boolean isAttacking() {
            int offset = myOffset + 275;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsAttacking(boolean value) {
            mainBuffer.buff.putByte(myOffset + 275, (byte) (value ? 1 : 0));
        }
        boolean isAttackFrame() {
            int offset = myOffset + 276;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsAttackFrame(boolean value) {
            mainBuffer.buff.putByte(myOffset + 276, (byte) (value ? 1 : 0));
        }
        boolean isBeingGathered() {
            int offset = myOffset + 277;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsBeingGathered(boolean value) {
            mainBuffer.buff.putByte(myOffset + 277, (byte) (value ? 1 : 0));
        }
        boolean isBlind() {
            int offset = myOffset + 278;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsBlind(boolean value) {
            mainBuffer.buff.putByte(myOffset + 278, (byte) (value ? 1 : 0));
        }
        boolean isBraking() {
            int offset = myOffset + 279;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsBraking(boolean value) {
            mainBuffer.buff.putByte(myOffset + 279, (byte) (value ? 1 : 0));
        }
        boolean isBurrowed() {
            int offset = myOffset + 280;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsBurrowed(boolean value) {
            mainBuffer.buff.putByte(myOffset + 280, (byte) (value ? 1 : 0));
        }
        int getCarryResourceType() {
            int offset = myOffset + 284;
            return wrapper.buff.getInt(offset);
        }
        void setCarryResourceType(int value) {
            mainBuffer.buff.putInt(myOffset + 284, value);
        }
        boolean isCloaked() {
            int offset = myOffset + 288;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsCloaked(boolean value) {
            mainBuffer.buff.putByte(myOffset + 288, (byte) (value ? 1 : 0));
        }
        boolean isCompleted() {
            int offset = myOffset + 289;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsCompleted(boolean value) {
            mainBuffer.buff.putByte(myOffset + 289, (byte) (value ? 1 : 0));
        }
        boolean isConstructing() {
            int offset = myOffset + 290;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsConstructing(boolean value) {
            mainBuffer.buff.putByte(myOffset + 290, (byte) (value ? 1 : 0));
        }
        boolean isDetected() {
            int offset = myOffset + 291;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsDetected(boolean value) {
            mainBuffer.buff.putByte(myOffset + 291, (byte) (value ? 1 : 0));
        }
        boolean isGathering() {
            int offset = myOffset + 292;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsGathering(boolean value) {
            mainBuffer.buff.putByte(myOffset + 292, (byte) (value ? 1 : 0));
        }
        boolean isHallucination() {
            int offset = myOffset + 293;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsHallucination(boolean value) {
            mainBuffer.buff.putByte(myOffset + 293, (byte) (value ? 1 : 0));
        }
        boolean isIdle() {
            int offset = myOffset + 294;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsIdle(boolean value) {
            mainBuffer.buff.putByte(myOffset + 294, (byte) (value ? 1 : 0));
        }
        boolean isInterruptible() {
            int offset = myOffset + 295;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsInterruptible(boolean value) {
            mainBuffer.buff.putByte(myOffset + 295, (byte) (value ? 1 : 0));
        }
        boolean isInvincible() {
            int offset = myOffset + 296;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsInvincible(boolean value) {
            mainBuffer.buff.putByte(myOffset + 296, (byte) (value ? 1 : 0));
        }
        boolean isLifted() {
            int offset = myOffset + 297;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsLifted(boolean value) {
            mainBuffer.buff.putByte(myOffset + 297, (byte) (value ? 1 : 0));
        }
        boolean isMorphing() {
            int offset = myOffset + 298;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsMorphing(boolean value) {
            mainBuffer.buff.putByte(myOffset + 298, (byte) (value ? 1 : 0));
        }
        boolean isMoving() {
            int offset = myOffset + 299;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsMoving(boolean value) {
            mainBuffer.buff.putByte(myOffset + 299, (byte) (value ? 1 : 0));
        }
        boolean isParasited() {
            int offset = myOffset + 300;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsParasited(boolean value) {
            mainBuffer.buff.putByte(myOffset + 300, (byte) (value ? 1 : 0));
        }
        boolean isSelected() {
            int offset = myOffset + 301;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsSelected(boolean value) {
            mainBuffer.buff.putByte(myOffset + 301, (byte) (value ? 1 : 0));
        }
        boolean isStartingAttack() {
            int offset = myOffset + 302;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsStartingAttack(boolean value) {
            mainBuffer.buff.putByte(myOffset + 302, (byte) (value ? 1 : 0));
        }
        boolean isStuck() {
            int offset = myOffset + 303;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsStuck(boolean value) {
            mainBuffer.buff.putByte(myOffset + 303, (byte) (value ? 1 : 0));
        }
        boolean isTraining() {
            int offset = myOffset + 304;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsTraining(boolean value) {
            mainBuffer.buff.putByte(myOffset + 304, (byte) (value ? 1 : 0));
        }
        boolean isUnderStorm() {
            int offset = myOffset + 305;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsUnderStorm(boolean value) {
            mainBuffer.buff.putByte(myOffset + 305, (byte) (value ? 1 : 0));
        }
        boolean isUnderDarkSwarm() {
            int offset = myOffset + 306;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsUnderDarkSwarm(boolean value) {
            mainBuffer.buff.putByte(myOffset + 306, (byte) (value ? 1 : 0));
        }
        boolean isUnderDWeb() {
            int offset = myOffset + 307;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsUnderDWeb(boolean value) {
            mainBuffer.buff.putByte(myOffset + 307, (byte) (value ? 1 : 0));
        }
        boolean isPowered() {
            int offset = myOffset + 308;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsPowered(boolean value) {
            mainBuffer.buff.putByte(myOffset + 308, (byte) (value ? 1 : 0));
        }
        boolean isVisible(int i) {
            int offset = myOffset + 309 + 1 * 1 * i;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setIsVisible(int i, boolean value) {
            mainBuffer.buff.putByte(myOffset + 309 + 1 * 1 * i, (byte) (value ? 1 : 0));
        }
        int getButtonset() {
            int offset = myOffset + 320;
            return wrapper.buff.getInt(offset);
        }
        void setButtonset(int value) {
            mainBuffer.buff.putInt(myOffset + 320, value);
        }
        int getLastAttackerPlayer() {
            int offset = myOffset + 324;
            return wrapper.buff.getInt(offset);
        }
        void setLastAttackerPlayer(int value) {
            mainBuffer.buff.putInt(myOffset + 324, value);
        }
        boolean getRecentlyAttacked() {
            int offset = myOffset + 328;
            return wrapper.buff.getByte(offset) != 0;
        }
        void setRecentlyAttacked(boolean value) {
            mainBuffer.buff.putByte(myOffset + 328, (byte) (value ? 1 : 0));
        }
        int getReplayID() {
            int offset = myOffset + 332;
            return wrapper.buff.getInt(offset);
        }
        void setReplayID(int value) {
            mainBuffer.buff.putInt(myOffset + 332, value);
        }
    }
}

